### ISSUE TITLE
Puma 6.0.0 does not close requests proxied to the Vite development server

### ISSUE THREAD

**Issue by ledermann** [ElMassimo/vite_ruby#299]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

After upgrading Puma to [v6.0.0](https://github.com/puma/puma/releases/tag/v6.0.0) I have issues in my Rails applications using `vite_ruby` in **development** mode: Full page reloading (or HMR) sometime fails with an endless loop. It requires all Ruby processes to quit and restart. After some time of file editing, it hangs again. The issue only occurs in apps using **both** Puma 6 and vite_ruby.

Reverting to Puma 5.6.5 helps, so It may be caused by Puma 6, not vite_ruby. 

### Reproduction 🐞

Not possible yet :-(

Of course, this is not helpful for troubleshooting or fixing, but maybe others can add their observations.

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 3.2.10
vite_rails: 3.0.12
rails: 7.0.4
node: v18.11.0
npm: 8.19.2
yarn: 1.22.19
pnpm: 7.12.2
ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

installed packages:
solectrus@0.1.0 /Users/ledermann/Projects/solectrus
├─┬ vite-plugin-full-reload@1.0.4
│ └── vite@3.2.2 deduped
├─┬ vite-plugin-ruby@3.1.2
│ └── vite@3.2.2 deduped
└── vite@3.2.2
```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_`DEBUG=vite-plugin-ruby:* bin/vite dev`_

```
  VITE v3.2.2  ready in 164 ms

  ➜  Local:   http://vite.solectrus.test:3036/vite-dev/
  ➜  Network: http://169.254.229.15:3036/vite-dev/
  ➜  Network: http://192.168.178.50:3036/vite-dev/
  ➜  Network: http://192.168.178.51:3036/vite-dev/
  ➜  Network: http://46.253.185.42:3036/vite-dev/
```
</details>

**Comment by marcoroth** [comment]
I'm also experiencing this. Trying to investigate.

**Comment by marcoroth** [comment]
Might be related to https://github.com/puma/puma/issues/2999

**Comment by marcoroth** [comment]
Puma 6.0.1 was released, which means this should also be resolved now 👍🏼

**Comment by jamesst20** [comment]
@ElMassimo I'm still experiencing this as of Puma 6.4.2. Any clue?

I found this thread from here and it appears i'm not alone with Puma 6.4.0+ 

https://stackoverflow.com/questions/59937524/rails-dev-server-takes-a-long-time-to-reload-after-codes-changes

**Comment by abuisman** [comment]
I am experiencing this as well and I am not using vite_ruby at all. 

So there must be something with puma. When I switched to Puma 5 it was resolved. But that shouldn't be the real solution.

**Comment by hulloitskai** [comment]
I'm also experiencing this issue! Working around it right now with `RAILS_MAX_THREADS=1` in development.
